dist: xenial
language: python
sudo: true
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
matrix:
    fast_finish: true
    include:
      - { python: "3.5", env: DJANGO_VERSION=1.11 }
      - { python: "3.5", env: DJANGO_VERSION=2.0 }
      - { python: "3.5", env: DJANGO_VERSION=2.1 }
      - { python: "3.5", env: DJANGO_VERSION=2.2 }

      - { python: "3.6", env: DJANGO_VERSION=1.11 }
      - { python: "3.6", env: DJANGO_VERSION=2.0 }
      - { python: "3.6", env: DJANGO_VERSION=2.1 }
      - { python: "3.6", env: DJANGO_VERSION=2.2 }

      - { python: "3.7", env: DJANGO_VERSION=2.0 }
      - { python: "3.7", env: DJANGO_VERSION=2.1 }
      - { python: "3.7", env: DJANGO_VERSION=2.2 }
before_install:
  - sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  - sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -q Django==$DJANGO_VERSION
  - pip install psycopg2

before_script:
  - psql -U postgres -c "create extension postgis"
script:
  - coverage run --source=mapbox_location_field manage.py test
after_success:
  - coveralls